<template>
  <div class="cursos_carrera" id="cursos">
    <h1>Cursos</h1>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime necessitatibus deleniti fugit et quia libero voluptatum iure temporibus rem soluta tenetur numquam laborum placeat, vitae dignissimos. Sint eaque sunt repellat?</p>
  </div>
</template>